### ISSUE TITLE
get_payment_status failing test

### ISSUE THREAD

**Issue by ntemple** [intellispire/commercestore#8]
## Bug Report

From test runner:

There was 1 failure:
--
  |  
  | 1) CS\Orders\Payment_Tests::test_get_payment_status
  | Failed asserting that false matches expected 'pending'.
  |  
  | /tmp/ojOdJdZ7s79PUiG2bP3h8OubiPFiRSK5/tests/orders/tests-payments.php:142
  | /tmp/ojOdJdZ7s79PUiG2bP3h8OubiPFiRSK5/vendor/phpunit/phpunit/phpunit:52

### Expected behavior
When I do run automated tests, I expect all of them to pass.

### Actual behavior
test_get_payment_status fails.

### Information (if a specific version is affected):
PHP Version: 7.4

CommerceStore Version (or branch): commercestore/main and commercestore/develop

WordPress Version: All

Any other relevant information:

There is a comment in the code that get_payment_status was recently refactored, I suspect that there is an actual code failure here.  Alternatively it could be a failure in the test runner to correctly mock a payment.

**Comment by intellispire** [comment]
Now fixed! Issue was that an index of "0" was being interpreted as "false".  Noe explicitly testing for that case.
